---
id: 'e1b8cfd0-d42d-4056-ac55-82a30f5bdffd'
title: 'Finish Tickets for Missing Patches'
title_meta: 'Finish Tickets for Missing Patches - ConnectWise Automate'
keywords: ['tickets', 'patches', 'monitor', 'automation', 'close']
description: 'This document outlines a script designed to automatically finish tickets generated by the Missing Patches detection solution for machines that are missing fewer than three patches or none at all. It includes a sample run, dependencies, and variable descriptions.'
tags: ['ticketing']
draft: false
unlisted: false
---
## Summary

The purpose of the script is to finish the new/open tickets created by the Missing Patches detection solution for the machines missing less than three or not missing any patches.

Affected Ticket Subject: `UPDATES - 3 Patches Missing on %ClientName%//%ComputerName%`

## Sample Run

![Sample Run](../../../static/img/Client-Specific---Auto-Close---Missing-Patch-Tickets-Autofix/image_1.png)

## Dependencies

[CWM - Internal Monitor - ProVal - Client Specific - Auto Close - Missing Patch Tickets](https://proval.itglue.com/DOC-5078775-12589460)

## Variables

| Name        | Description                                      |
|-------------|--------------------------------------------------|
| STATUS      | Status returned by the monitor set (FAILED/SUCCESS) |
| Count       | Number of tickets to finish                       |
| SQLTicketid | Ticketid to finish/close                         |











